'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class errors
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("projectSettings.errors", GetType(errors).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hash validation incorrect..
        '''</summary>
        Friend Shared ReadOnly Property API_LOGINIMPLEMENTATION_000() As String
            Get
                Return ResourceManager.GetString("API_LOGINIMPLEMENTATION_000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Petition has expired..
        '''</summary>
        Friend Shared ReadOnly Property API_LOGINIMPLEMENTATION_001() As String
            Get
                Return ResourceManager.GetString("API_LOGINIMPLEMENTATION_001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Device identifier missing..
        '''</summary>
        Friend Shared ReadOnly Property API_LOGINIMPLEMENTATION_002() As String
            Get
                Return ResourceManager.GetString("API_LOGINIMPLEMENTATION_002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing timestamp parameter..
        '''</summary>
        Friend Shared ReadOnly Property API_LOGINIMPLEMENTATION_003() As String
            Get
                Return ResourceManager.GetString("API_LOGINIMPLEMENTATION_003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing email parameter..
        '''</summary>
        Friend Shared ReadOnly Property API_LOGINIMPLEMENTATION_004() As String
            Get
                Return ResourceManager.GetString("API_LOGINIMPLEMENTATION_004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paramerter {0} must be filled..
        '''</summary>
        Friend Shared ReadOnly Property API_PARAMETERVALIDATIONS_000() As String
            Get
                Return ResourceManager.GetString("API_PARAMETERVALIDATIONS_000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameter {0} must be a number..
        '''</summary>
        Friend Shared ReadOnly Property API_PARAMETERVALIDATIONS_001() As String
            Get
                Return ResourceManager.GetString("API_PARAMETERVALIDATIONS_001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Token {0} has expired or it&apos;s not valid..
        '''</summary>
        Friend Shared ReadOnly Property GENERAL_998() As String
            Get
                Return ResourceManager.GetString("GENERAL_998", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Readonly property..
        '''</summary>
        Friend Shared ReadOnly Property GENERAL_999() As String
            Get
                Return ResourceManager.GetString("GENERAL_999", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A company named {0} already exists. Please select another..
        '''</summary>
        Friend Shared ReadOnly Property MODEL_COMPANIESBRAIN_000() As String
            Get
                Return ResourceManager.GetString("MODEL_COMPANIESBRAIN_000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company ID cannot be modified..
        '''</summary>
        Friend Shared ReadOnly Property MODEL_COMPANIESBRAIN_001() As String
            Get
                Return ResourceManager.GetString("MODEL_COMPANIESBRAIN_001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fileId cannot be modified..
        '''</summary>
        Friend Shared ReadOnly Property MODEL_FILESBRAIN_000() As String
            Get
                Return ResourceManager.GetString("MODEL_FILESBRAIN_000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File with id {0} does not exist..
        '''</summary>
        Friend Shared ReadOnly Property MODEL_FILESBRAIN_001() As String
            Get
                Return ResourceManager.GetString("MODEL_FILESBRAIN_001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password incorrect for user {0}..
        '''</summary>
        Friend Shared ReadOnly Property MODEL_TOKENSBRAIN_000() As String
            Get
                Return ResourceManager.GetString("MODEL_TOKENSBRAIN_000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User {0} already exists..
        '''</summary>
        Friend Shared ReadOnly Property MODEL_USERSBRAIN_000() As String
            Get
                Return ResourceManager.GetString("MODEL_USERSBRAIN_000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User  ID cannot be modified..
        '''</summary>
        Friend Shared ReadOnly Property MODEL_USERSBRAIN_001() As String
            Get
                Return ResourceManager.GetString("MODEL_USERSBRAIN_001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User with ID {0} does not exist..
        '''</summary>
        Friend Shared ReadOnly Property MODEL_USERSBRAIN_002() As String
            Get
                Return ResourceManager.GetString("MODEL_USERSBRAIN_002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User with email {0} does not exist..
        '''</summary>
        Friend Shared ReadOnly Property MODEL_USERSBRAIN_003() As String
            Get
                Return ResourceManager.GetString("MODEL_USERSBRAIN_003", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
